
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RBRACK = 14;
  public static final int SEMICOLON = 17;
  public static final int CLASS = 3;
  public static final int PLUS = 6;
  public static final int RBRACE = 16;
  public static final int RPAREN = 12;
  public static final int LBRACK = 13;
  public static final int MULTI = 8;
  public static final int IDENTIFIER = 18;
  public static final int LPAREN = 11;
  public static final int LBRACE = 15;
  public static final int STRING = 5;
  public static final int NUMBER = 19;
  public static final int EOF = 0;
  public static final int MAIN = 4;
  public static final int DIV = 9;
  public static final int MINUS = 7;
  public static final int error = 1;
  public static final int DISPLAY = 2;
  public static final int BOOL = 20;
  public static final int BECOMES = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DISPLAY",
  "CLASS",
  "MAIN",
  "STRING",
  "PLUS",
  "MINUS",
  "MULTI",
  "DIV",
  "BECOMES",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "LBRACE",
  "RBRACE",
  "SEMICOLON",
  "IDENTIFIER",
  "NUMBER",
  "BOOL"
  };
}

